Cue: don't panic!
zorp-corp/sword pull request #262
Opened 2024-09-06 04:32 UTC by eamsden

Rewrite cue to return deterministic or nondeterministic errors, as appropriate.

2024-09-07 02:54 UTC, tacryt-socryp commented on rust/sword/src/serialization.rs
> +                unsafe { stack.pop::<*mut Noun>(); };
Can't read 65-72 for shit. No clue what's happening

2024-09-07 17:05 UTC, bitemyapp commented on rust/sword/src/jets/serial.rs
> +    Ok(cue(&mut context.stack, slot(subject, 6)?.as_atom()?)?)
Ok(...?) is usually unnecessary? I'd expect `cargo lint` to have picked this up. let me check.

2024-09-07 17:25 UTC, bitemyapp commented on rust/sword/src/jets/serial.rs
> +    Ok(cue(&mut context.stack, slot(subject, 6)?.as_atom()?)?)
I was wrong, you're converting the error.

2024-09-07 17:27 UTC, bitemyapp commented on rust/sword/src/newt.rs
> +        Some(cue(stack, atom).expect("bad jammed noun"))
I'm adding some prefixes to these panics in the other branch, but why not have `next()` return `Result<Option<...>>` if it's fallible?

2024-09-07 17:29 UTC, bitemyapp commented on rust/sword/src/serialization.rs
> +                unsafe { stack.pop::<*mut Noun>(); };
I think 65-72 is part of a segment I cleaned up in my distaff branch. You don't have to `unsafe` code that is already inside an outer unsafe block.

![image](https://github.com/user-attachments/assets/2bafb8c8-39e4-47de-9830-8b0b7a9b7a04)

This section needs inline comments, I agree. I'm going to start tagging things with // TODO: comments.

2024-09-07 17:34 UTC, bitemyapp commented on rust/sword/src/serialization.rs
> +        .ok_or(Deterministic(Exit, D(0)))?;
veddy good

2024-09-09 13:00 UTC, ryjm commented on rust/sword/src/serialization.rs
> +                unsafe { stack.pop::<*mut Noun>(); };
#266 added some here

2024-09-09 17:06 UTC, drbeefsupreme requested changes
Looking good, pending merge of #266

2024-09-09 20:12 UTC, eamsden commented on rust/sword/src/serialization.rs
> +                unsafe { stack.pop::<*mut Noun>(); };
@tacryt-socryp please re-review now

2024-09-09 20:13 UTC, eamsden commented on rust/sword/src/newt.rs
> +        Some(cue(stack, atom).expect("bad jammed noun"))
Because this code is going away in another PR soon, so idc except that it compiles

2024-09-09 20:14 UTC, eamsden commented on rust/sword/src/serialization.rs
> +}
Perhaps it should be called `next_up_to_n_bits()`

2024-09-09 20:14 UTC, eamsden commented on rust/sword/src/serialization.rs
> +fn rub_atom(stack: &mut NockStack, cursor: &mut usize, buffer: &BitSlice<u64, Lsb0>) -> Result<Atom,Error> {
This will be determined by `cargo format`

2024-09-09 20:44 UTC, drbeefsupreme commented on rust/sword/src/serialization.rs
> +}
Yeah just changing the name would be enough to make me happy.

2024-09-09 20:46 UTC, drbeefsupreme commented
What's the short explanation on what's going on with the `ibig` changes?

2024-09-09 20:55 UTC, drbeefsupreme requested changes

2024-09-09 20:55 UTC, drbeefsupreme commented on rust/sword/src/serialization.rs
> +    if stack_size < input_size {
I probably should have been more explicit on my comments on @ryjm's PR. `stack.size()` will return a size in machinewords, while `buffer.len()` will return a size in bits. So this needs to be altered.

2024-10-03 03:24 UTC, eamsden commented on rust/sword/src/serialization.rs
> +    if stack_size < input_size {
This check should be removed: a cue buffer can construct a noun bigger than the buffer. The size could be computed by a pre-traversal pass, but it's better to just let nockstack's internal OOM-handling catch this

2024-10-04 19:58 UTC, drbeefsupreme approved these changes

2024-10-04 22:17 UTC, merged