Hamt Iterator
zorp-corp/sword pull request #271
Opened 2024-10-04 19:53 UTC by bitemyapp

![image](https://github.com/user-attachments/assets/f8a685bc-855e-4296-b15c-e6fc5513bc8b)

First pass at the Hamt iterator. My understanding was we didn't need this for `MutHamt` so I didn't bother there. Max depth is 6 AIUI so the traversal stack is a fixed array.

2024-10-07 21:15 UTC, drbeefsupreme requested changes
One possible bug, one style issue

2024-10-07 21:15 UTC, drbeefsupreme commented on rust/sword/src/hamt.rs
> +            if self.depth == usize::MAX {
This seems like an unusual condition to exit a loop. It looks like it works fine, but is there a reason to use this over checking if `depth == 0` and returning `None` on line 840 instead?

2024-10-07 21:15 UTC, drbeefsupreme commented on rust/sword/src/hamt.rs
> +                    }
A `Leaf` can have more than one key-value pair, see L414-433. Does this handle that case? It looks like it only handles the single pair case.

2024-10-07 21:27 UTC, bitemyapp commented on rust/sword/src/hamt.rs
> +            if self.depth == usize::MAX {
It's using `.wrapping_sub(1)` to detect when it's done. I realize this looks odd but rejiggering it to use a zero-based "done" is more annoying than you'd guess. Depth starts at zero, it never iterates if you change it to `== 0` with no other changes.

2024-10-07 21:28 UTC, bitemyapp commented on rust/sword/src/hamt.rs
> +                    }
Let me construct a regression test for this so that I know when I've actually fixed it. Thank you!

2024-10-08 20:39 UTC, drbeefsupreme approved these changes

2024-10-08 20:39 UTC, drbeefsupreme commented
LGTM

2024-10-08 22:07 UTC, drbeefsupreme reviewed
Latest commit looks good except for `default()` which I defer to @eamsden

2024-10-08 22:07 UTC, drbeefsupreme commented on rust/sword/src/hamt.rs
> +    }
Comment this out again?

2024-10-08 22:07 UTC, drbeefsupreme commented on rust/sword/src/noun.rs
> +        Noun { raw: u64::MAX }
I do not want to merge this without @eamsden taking a look at this.

2024-10-09 18:07 UTC, eamsden commented on rust/sword/src/hamt.rs
> +                                    len: leaf.len + 1,
OOF

Good catch boys @bitemyapp @drbeefsupreme

2024-10-09 19:44 UTC, eamsden approved these changes

2024-10-09 19:44 UTC, merged